# TODO: Напишите пайплайн для автоматической сборки и деплоя приложения
#
# В качестве подсказки, начало файла может выглядеть так:
#
# name: CI/CD Pipeline
#
# on:
#   push:
#     branches:
#       - main
#       - cicd_example
#   workflow_dispatch:
#
